# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-XML
version:      2.17
version_from: lib/Template/Plugin/XML.pm
installdirs:  site
requires:
    Template:                      2.15
    XML::DOM:                      1.27
    XML::Parser:                   2.19
    XML::RSS:                      0.9
    XML::Simple:                   2
    XML::XPath:                    1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
